apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: argocdappdemo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: argocdappdemo
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      ports: 80
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  # Intentional Schema Validation Issue
  # The 'replicas' field is not valid for a Pod specification.
  replicas: 3

