apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secondapp
spec:
  destination:
    name: ''
    namespace: selfheal
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo-Files/Nginx-Deployment
    repoURL: 'https://github.com/SMACAcademy/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
